INSERT INTO MERCHANT VALUES (1, 'ACTIVE', 1); 
INSERT INTO MERCHANT VALUES (2, 'ACTIVE', 1);
INSERT INTO MERCHANT VALUES (3, 'INACTIVE', 1);
INSERT INTO MERCHANT_AGREEMENT VALUES(2, 'EUR', 1);
INSERT INTO MERCHANT_AGREEMENT VALUES(4, 'JPY', 1);
INSERT INTO MERCHANT_AGREEMENT VALUES(3, 'GBP', 2);